version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-pagamentos
    #network_mode: 'host'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - /home/ylan/development/docker-compose/mysql-pagamentos:/var/lib/mysql
volumes:
  mysql-pagamentos:
    driver: local